[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# Optimizer settings to fix "stack too deep" errors
via_ir = true
optimizer = true
optimizer_runs = 200

# Scroll Sepolia configuration
[rpc_endpoints]
scroll_sepolia = "https://sepolia-rpc.scroll.io"

[etherscan]
scroll_sepolia = { key = "${SCROLLSCAN_API_KEY}", url = "https://api-sepolia.scrollscan.com/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Optional alternative profile without Yul IR, in case some deployments were built without it
[profile.no_ir]
via_ir = false
optimizer = true
optimizer_runs = 200
