[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# Optimizer settings to fix "stack too deep" errors
via_ir = true
optimizer = true
optimizer_runs = 200

# Morph Holesky configuration
[rpc_endpoints]
morph_holesky = "https://rpc-holesky.morphl2.io"

[etherscan]
morph_holesky = { key = "", url = "https://explorer-holesky.morphl2.io/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
